version: '3.8'
                  
services:
    training-redis-master:
        image: bitnami/redis:latest
        environment:
            - REDIS_REPLICATION_MODE=master
            - ALLOW_EMPTY_PASSWORD=yes
        container_name: training-redis
        expose:
            - '6379'
        volumes:
            - /bitnami/redis/data 
        networks:
            - training-internal
        restart: always