version: '3.8'
                  
services:
    training-api:
        image: training-api
        environment:
            - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
        container_name: training-api
        build:
            dockerfile: ./DockerTraining/Dockerfile
            context: .
        ports:
            - '8000:8000'
        networks:
            - training
        restart: unless-stopped
              
networks:
    training:
        driver: bridge
    training-internal:
        driver: bridge