version: '3.8'
                  
services:
    training-guid-generator:
        image: training-guid-generator
        environment:
            - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
        container_name: training-guid-generator
        build:
            dockerfile: ./DockerTraining.GuidGeneratorService/Dockerfile
            context: .
        expose:
            - '8001'
        networks:
            - training
            - training-internal
        depends_on:
            - training-redis-master
        restart: unless-stopped